name: teaching_with_purpose_student
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.3.3
  google_fonts: ^6.1.0
  new_version_plus: ^0.0.11
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  flutter_gen_runner: ^5.1.0+1
  percent_indicator: ^4.2.3
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9
  connectivity_plus: ^5.0.1
  intl: ^0.18.1
  firebase_auth: ^4.15.0
  stacked_firebase_auth: ^2.19.6
  firebase_core: ^2.24.0
  file_picker: ^6.1.1
  chewie: ^1.2.0
  video_player: ^2.3.3
  path_provider: ^2.0.15
  permission_handler: ^11.1.0
  open_file: ^3.3.2


dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_test: 
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottiefiles/
    - assets/svg/
    - assets/icons/



icons_launcher:
  image_path: "assets/images/splash.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

