///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AssignmentsListModelData {
/*
{
  "_id": "654ccf1e3516875670308668",
  "subject": "english",
  "class": "7-A",
  "title": "Essay on Global Warming",
  "desc": "Write an essay discussing the impact of global warming on the environment.",
  "totalMarks": "50",
  "dueDate": "2023-12-01T00:00:00.000Z",
  "uploadFile": "https://example.com/global-warming-essay.pdf",
  "isAssign": true,
  "isSubmit": false,
  "isDeleted": false,
  "createdAt": "2023-11-09T12:22:54.773Z",
  "updatedAt": "2023-11-09T12:40:36.244Z",
  "__v": 0
} 
*/

  String? Id;
  String? subject;
  String? theClass;
  String? title;
  String? desc;
  String? totalMarks;
  String? dueDate;
  String? uploadFile;
  bool? isAssign;
  bool? isSubmit;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  AssignmentsListModelData({
    this.Id,
    this.subject,
    this.theClass,
    this.title,
    this.desc,
    this.totalMarks,
    this.dueDate,
    this.uploadFile,
    this.isAssign,
    this.isSubmit,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  AssignmentsListModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    theClass = json['class']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    totalMarks = json['totalMarks']?.toString();
    dueDate = json['dueDate']?.toString();
    uploadFile = json['uploadFile']?.toString();
    isAssign = json['isAssign'];
    isSubmit = json['isSubmit'];
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class AssignmentsListModel {
/*
{
  "status": true,
  "result": 1,
  "data": [
    {
      "_id": "654ccf1e3516875670308668",
      "subject": "english",
      "class": "7-A",
      "title": "Essay on Global Warming",
      "desc": "Write an essay discussing the impact of global warming on the environment.",
      "totalMarks": "50",
      "dueDate": "2023-12-01T00:00:00.000Z",
      "uploadFile": "https://example.com/global-warming-essay.pdf",
      "isAssign": true,
      "isSubmit": false,
      "isDeleted": false,
      "createdAt": "2023-11-09T12:22:54.773Z",
      "updatedAt": "2023-11-09T12:40:36.244Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<AssignmentsListModelData?>? data;

  AssignmentsListModel({
    this.status,
    this.result,
    this.data,
  });
  AssignmentsListModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <AssignmentsListModelData>[];
  v.forEach((v) {
  arr0.add(AssignmentsListModelData.fromJson(v));
  });
    data = arr0;
    }
  }
}
