///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChaptersModelData {
/*
{
  "_id": "658aa2a1bfee16190abc9b12",
  "subjectId": "6570261b8c2337e8d3e2e313",
  "chapterName": "Chapter three",
  "concept": "Story teller",
  "desc": "we discuss about story",
  "video": "https://angolazone.s3.ap-south-1.amazonaws.com/angolazone-SampleVideo_1280x720_1mb.mp4",
  "uploadPdf": "https://angolazone.s3.ap-south-1.amazonaws.com/angolazone-english.pdf",
  "isDeleted": false,
  "createdAt": "2023-12-26T09:53:37.539Z",
  "updatedAt": "2023-12-26T09:53:37.539Z",
  "__v": 0
} 
*/

  String? Id;
  String? subjectId;
  String? chapterName;
  String? concept;
  String? desc;
  String? video;
  String? uploadPdf;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ChaptersModelData({
    this.Id,
    this.subjectId,
    this.chapterName,
    this.concept,
    this.desc,
    this.video,
    this.uploadPdf,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ChaptersModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    subjectId = json['subjectId']?.toString();
    chapterName = json['chapterName']?.toString();
    concept = json['concept']?.toString();
    desc = json['desc']?.toString();
    video = json['video']?.toString();
    uploadPdf = json['uploadPdf']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['subjectId'] = subjectId;
    data['chapterName'] = chapterName;
    data['concept'] = concept;
    data['desc'] = desc;
    data['video'] = video;
    data['uploadPdf'] = uploadPdf;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}
