///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChapterQuestionsModelDataQuestion {
/*
{
  "questionText": "What are the roots of the equation x^2 - 5x + 6 = 0?",
  "options": [
    " x = 2, x = 3"
  ],
  "solution": " x = 2, x = 3",
  "_id": "65c37fa783c0e641ebc0d6c7"
} 
*/

  String? questionText;
  List<String?>? options;
  String? solution;
  String? Id;

  ChapterQuestionsModelDataQuestion({
    this.questionText,
    this.options,
    this.solution,
    this.Id,
  });
  ChapterQuestionsModelDataQuestion.fromJson(Map<String, dynamic> json) {
    questionText = json['questionText']?.toString();
  if (json['options'] != null) {
  final v = json['options'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    options = arr0;
    }
    solution = json['solution']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['questionText'] = questionText;
    if (options != null) {
      final v = options;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['options'] = arr0;
    }
    data['solution'] = solution;
    data['_id'] = Id;
    return data;
  }
}

class ChapterQuestionsModelData {
/*
{
  "_id": "65c37fa783c0e641ebc0d6c6",
  "chapterId": "65c37f8183c0e641ebc0d6c3",
  "question": [
    {
      "questionText": "What are the roots of the equation x^2 - 5x + 6 = 0?",
      "options": [
        " x = 2, x = 3"
      ],
      "solution": " x = 2, x = 3",
      "_id": "65c37fa783c0e641ebc0d6c7"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-02-07T13:03:35.077Z",
  "updatedAt": "2024-02-07T13:03:35.077Z",
  "__v": 0
} 
*/

  String? Id;
  String? chapterId;
  List<ChapterQuestionsModelDataQuestion?>? question;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ChapterQuestionsModelData({
    this.Id,
    this.chapterId,
    this.question,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ChapterQuestionsModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    chapterId = json['chapterId']?.toString();
  if (json['question'] != null) {
  final v = json['question'];
  final arr0 = <ChapterQuestionsModelDataQuestion>[];
  v.forEach((v) {
  arr0.add(ChapterQuestionsModelDataQuestion.fromJson(v));
  });
    question = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['chapterId'] = chapterId;
    if (question != null) {
      final v = question;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['question'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class ChapterQuestionsModel {
/*
{
  "status": true,
  "result": 9,
  "data": [
    {
      "_id": "65c37fa783c0e641ebc0d6c6",
      "chapterId": "65c37f8183c0e641ebc0d6c3",
      "question": [
        {
          "questionText": "What are the roots of the equation x^2 - 5x + 6 = 0?",
          "options": [
            " x = 2, x = 3"
          ],
          "solution": " x = 2, x = 3",
          "_id": "65c37fa783c0e641ebc0d6c7"
        }
      ],
      "isDeleted": false,
      "createdAt": "2024-02-07T13:03:35.077Z",
      "updatedAt": "2024-02-07T13:03:35.077Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ChapterQuestionsModelData?>? data;

  ChapterQuestionsModel({
    this.status,
    this.result,
    this.data,
  });
  ChapterQuestionsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ChapterQuestionsModelData>[];
  v.forEach((v) {
  arr0.add(ChapterQuestionsModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}


