

import 'package:teaching_with_purpose_student/app/data/models/days_table_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ClassScheduleModelDataClassFaculity {
/*
{
  "subjectTeacher": "def",
  "subject": "math",
  "_id": "657a8a86733ad22fc6a06edf"
} 
*/

  String? subjectTeacher;
  String? subject;
  String? Id;

  ClassScheduleModelDataClassFaculity({
    this.subjectTeacher,
    this.subject,
    this.Id,
  });
  ClassScheduleModelDataClassFaculity.fromJson(Map<String, dynamic> json) {
    subjectTeacher = json['subjectTeacher']?.toString();
    subject = json['subject']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subjectTeacher'] = subjectTeacher;
    data['subject'] = subject;
    data['_id'] = Id;
    return data;
  }
}

class ClassScheduleModelData {
/*
{
  "_id": "657a8a86733ad22fc6a06ede",
  "calssTeacher": "abc",
  "className": "8-A",
  "subject": "english",
  "classCapcity": 30,
  "classFaculity": [
    {
      "subjectTeacher": "def",
      "subject": "math",
      "_id": "657a8a86733ad22fc6a06edf"
    }
  ],
  "timeTable": [
    {
      "time": "10am-11am",
      "day": "monday",
      "subjectTeacher": "abc",
      "_id": "657a8a86733ad22fc6a06ee1"
    }
  ],
  "isDeleted": false,
  "createdAt": "2023-12-14T04:54:30.121Z",
  "updatedAt": "2023-12-14T05:10:10.358Z",
  "__v": 0
} 
*/

  String? Id;
  String? calssTeacher;
  String? className;
  String? subject;
  int? classCapcity;
  List<ClassScheduleModelDataClassFaculity?>? classFaculity;
  List<DaysTableModel>? timeTable;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleModelData({
    this.Id,
    this.calssTeacher,
    this.className,
    this.subject,
    this.classCapcity,
    this.classFaculity,
    this.timeTable,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    calssTeacher = json['calssTeacher']?.toString();
    className = json['className']?.toString();
    subject = json['subject']?.toString();
    classCapcity = json['classCapcity']?.toInt();
  if (json['classFaculity'] != null) {
  final v = json['classFaculity'];
  final arr0 = <ClassScheduleModelDataClassFaculity>[];
  v.forEach((v) {
  arr0.add(ClassScheduleModelDataClassFaculity.fromJson(v));
  });
    classFaculity = arr0;
    }
  if (json['timeTable'] != null) {
  final v = json['timeTable'];
  final arr0 = <DaysTableModel>[];
  v.forEach((v) {
  arr0.add(DaysTableModel.fromJson(v));
  });
    timeTable = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['calssTeacher'] = calssTeacher;
    data['className'] = className;
    data['subject'] = subject;
    data['classCapcity'] = classCapcity;
    if (classFaculity != null) {
      final v = classFaculity;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['classFaculity'] = arr0;
    }
    if (timeTable != null) {
      final v = timeTable;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v.toJson());
  }
      data['timeTable'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class ClassScheduleModel {
/*
{
  "status": true,
  "result": 5,
  "data": [
    {
      "_id": "657a8a86733ad22fc6a06ede",
      "calssTeacher": "abc",
      "className": "8-A",
      "subject": "english",
      "classCapcity": 30,
      "classFaculity": [
        {
          "subjectTeacher": "def",
          "subject": "math",
          "_id": "657a8a86733ad22fc6a06edf"
        }
      ],
      "timeTable": [
        {
          "time": "10am-11am",
          "day": "monday",
          "subjectTeacher": "abc",
          "_id": "657a8a86733ad22fc6a06ee1"
        }
      ],
      "isDeleted": false,
      "createdAt": "2023-12-14T04:54:30.121Z",
      "updatedAt": "2023-12-14T05:10:10.358Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ClassScheduleModelData?>? data;

  ClassScheduleModel({
    this.status,
    this.result,
    this.data,
  });
  ClassScheduleModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ClassScheduleModelData>[];
  v.forEach((v) {
  arr0.add(ClassScheduleModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
