///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuestionsModelData {
/*
{
  "_id": "658aa301bfee16190abc9b15",
  "question": "who the girl coming from death the the story",
  "option": [
    "jenni"
  ],
  "chapterId": "6570261b8c2337e8d3e2e313",
  "solution": "jan",
  "isDeleted": false,
  "createdAt": "2023-12-26T09:55:13.670Z",
  "updatedAt": "2023-12-26T09:55:13.670Z",
  "__v": 0
} 
*/

  String? Id;
  String? question;
  List<String?>? option;
  String? chapterId;
  String? solution;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  QuestionsModelData({
    this.Id,
    this.question,
    this.option,
    this.chapterId,
    this.solution,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  QuestionsModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    question = json['question']?.toString();
  if (json['option'] != null) {
  final v = json['option'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    option = arr0;
    }
    chapterId = json['chapterId']?.toString();
    solution = json['solution']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['question'] = question;
    if (option != null) {
      final v = option;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['option'] = arr0;
    }
    data['chapterId'] = chapterId;
    data['solution'] = solution;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class QuestionsModel {
/*
{
  "status": true,
  "result": 10,
  "data": [
    {
      "_id": "658aa301bfee16190abc9b15",
      "question": "who the girl coming from death the the story",
      "option": [
        "jenni"
      ],
      "chapterId": "6570261b8c2337e8d3e2e313",
      "solution": "jan",
      "isDeleted": false,
      "createdAt": "2023-12-26T09:55:13.670Z",
      "updatedAt": "2023-12-26T09:55:13.670Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<QuestionsModelData?>? data;

  QuestionsModel({
    this.status,
    this.result,
    this.data,
  });
  QuestionsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <QuestionsModelData>[];
  v.forEach((v) {
  arr0.add(QuestionsModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
