

import 'package:teaching_with_purpose_student/app/data/models/questions_model_data.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class QuestionsModel {
/*
{
  "status": true,
  "result": 10,
  "data": [
    {
      "_id": "658aa301bfee16190abc9b15",
      "question": "who the girl coming from death the the story",
      "option": [
        "jenni"
      ],
      "chapterId": "6570261b8c2337e8d3e2e313",
      "solution": "jan",
      "isDeleted": false,
      "createdAt": "2023-12-26T09:55:13.670Z",
      "updatedAt": "2023-12-26T09:55:13.670Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<QuestionsModelData?>? data;

  QuestionsModel({
    this.status,
    this.result,
    this.data,
  });
  QuestionsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <QuestionsModelData>[];
  v.forEach((v) {
  arr0.add(QuestionsModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
