///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuizzModelDataQuestion {
/*
{
  "questionText": "What is 2 + 2?",
  "answer": 4,
  "points": 5,
  "options": [
    "3"
  ],
  "_id": "65780608b98ace3f153e8971"
} 
*/

  String? questionText;
  int? answer;
  int? points;
  List<String?>? options;
  String? Id;

  QuizzModelDataQuestion({
    this.questionText,
    this.answer,
    this.points,
    this.options,
    this.Id,
  });
  QuizzModelDataQuestion.fromJson(Map<String, dynamic> json) {
    questionText = json['questionText']?.toString();
    answer = json['answer']?.toInt();
    points = json['points']?.toInt();
  if (json['options'] != null) {
  final v = json['options'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    options = arr0;
    }
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['questionText'] = questionText;
    data['answer'] = answer;
    data['points'] = points;
    if (options != null) {
      final v = options;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['options'] = arr0;
    }
    data['_id'] = Id;
    return data;
  }
}

class QuizzModelDataConductedBy {
/*
{
  "_id": "657021118c2337e8d3e2e307",
  "name": "John Doe",
  "__t": "Teachers"
} 
*/

  String? Id;
  String? name;
  String? T;

  QuizzModelDataConductedBy({
    this.Id,
    this.name,
    this.T,
  });
  QuizzModelDataConductedBy.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    T = json['__t']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    data['__t'] = T;
    return data;
  }
}

class QuizzModelData {
/*
{
  "_id": "65780608b98ace3f153e8970",
  "subject": "english",
  "conductedBy": {
    "_id": "657021118c2337e8d3e2e307",
    "name": "John Doe",
    "__t": "Teachers"
  },
  "date": "2023-11-23",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-th.jpg",
  "topicCover": [
    "watt"
  ],
  "instructions": "Read the questions carefully.",
  "question": [
    {
      "questionText": "What is 2 + 2?",
      "answer": 4,
      "points": 5,
      "options": [
        "3"
      ],
      "_id": "65780608b98ace3f153e8971"
    }
  ],
  "isDeleted": false,
  "createdAt": "2023-12-12T07:04:40.882Z",
  "updatedAt": "2023-12-12T07:04:40.882Z",
  "__v": 0
} 
*/

  String? Id;
  String? subject;
  QuizzModelDataConductedBy? conductedBy;
  String? date;
  String? image;
  List<String?>? topicCover;
  String? instructions;
  List<QuizzModelDataQuestion?>? question;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  QuizzModelData({
    this.Id,
    this.subject,
    this.conductedBy,
    this.date,
    this.image,
    this.topicCover,
    this.instructions,
    this.question,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  QuizzModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    conductedBy = (json['conductedBy'] != null) ? QuizzModelDataConductedBy.fromJson(json['conductedBy']) : null;
    date = json['date']?.toString();
    image = json['image']?.toString();
  if (json['topicCover'] != null) {
  final v = json['topicCover'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    topicCover = arr0;
    }
    instructions = json['instructions']?.toString();
  if (json['question'] != null) {
  final v = json['question'];
  final arr0 = <QuizzModelDataQuestion>[];
  v.forEach((v) {
  arr0.add(QuizzModelDataQuestion.fromJson(v));
  });
    question = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['subject'] = subject;
    if (conductedBy != null) {
      data['conductedBy'] = conductedBy!.toJson();
    }
    data['date'] = date;
    data['image'] = image;
    if (topicCover != null) {
      final v = topicCover;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['topicCover'] = arr0;
    }
    data['instructions'] = instructions;
    if (question != null) {
      final v = question;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['question'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class QuizzModel {
/*
{
  "status": true,
  "result": 2,
  "data": [
    {
      "_id": "65780608b98ace3f153e8970",
      "subject": "english",
      "conductedBy": {
        "_id": "657021118c2337e8d3e2e307",
        "name": "John Doe",
        "__t": "Teachers"
      },
      "date": "2023-11-23",
      "image": "https://angolazone.s3.amazonaws.com/angolazone-th.jpg",
      "topicCover": [
        "watt"
      ],
      "instructions": "Read the questions carefully.",
      "question": [
        {
          "questionText": "What is 2 + 2?",
          "answer": 4,
          "points": 5,
          "options": [
            "3"
          ],
          "_id": "65780608b98ace3f153e8971"
        }
      ],
      "isDeleted": false,
      "createdAt": "2023-12-12T07:04:40.882Z",
      "updatedAt": "2023-12-12T07:04:40.882Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<QuizzModelData?>? data;

  QuizzModel({
    this.status,
    this.result,
    this.data,
  });
  QuizzModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <QuizzModelData>[];
  v.forEach((v) {
  arr0.add(QuizzModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
