///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReviceQuestionsmodelDataQuestion {
/*
{
  "questionText": "What is the capital of France?",
  "answer": 2,
  "options": [
    "London"
  ],
  "solution": "The capital of France is Paris.",
  "_id": "65c238ea3713e39372b580c0"
} 
*/

  String? questionText;
  int? answer;
  List<String?>? options;
  String? solution;
  String? Id;

  ReviceQuestionsmodelDataQuestion({
    this.questionText,
    this.answer,
    this.options,
    this.solution,
    this.Id,
  });
  ReviceQuestionsmodelDataQuestion.fromJson(Map<String, dynamic> json) {
    questionText = json['questionText']?.toString();
    answer = json['answer']?.toInt();
  if (json['options'] != null) {
  final v = json['options'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    options = arr0;
    }
    solution = json['solution']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['questionText'] = questionText;
    data['answer'] = answer;
    if (options != null) {
      final v = options;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['options'] = arr0;
    }
    data['solution'] = solution;
    data['_id'] = Id;
    return data;
  }
}

class ReviceQuestionsmodelData {
/*
{
  "_id": "65c238ea3713e39372b580bf",
  "chapterId": "65c238d93713e39372b580bc",
  "question": [
    {
      "questionText": "What is the capital of France?",
      "answer": 2,
      "options": [
        "London"
      ],
      "solution": "The capital of France is Paris.",
      "_id": "65c238ea3713e39372b580c0"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-02-06T13:49:30.305Z",
  "updatedAt": "2024-02-06T13:49:30.305Z",
  "__v": 0
} 
*/

  String? Id;
  String? chapterId;
  List<ReviceQuestionsmodelDataQuestion?>? question;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ReviceQuestionsmodelData({
    this.Id,
    this.chapterId,
    this.question,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ReviceQuestionsmodelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    chapterId = json['chapterId']?.toString();
  if (json['question'] != null) {
  final v = json['question'];
  final arr0 = <ReviceQuestionsmodelDataQuestion>[];
  v.forEach((v) {
  arr0.add(ReviceQuestionsmodelDataQuestion.fromJson(v));
  });
    question = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['chapterId'] = chapterId;
    if (question != null) {
      final v = question;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['question'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class ReviceQuestionsmodel {
/*
{
  "status": true,
  "result": 3,
  "data": [
    {
      "_id": "65c238ea3713e39372b580bf",
      "chapterId": "65c238d93713e39372b580bc",
      "question": [
        {
          "questionText": "What is the capital of France?",
          "answer": 2,
          "options": [
            "London"
          ],
          "solution": "The capital of France is Paris.",
          "_id": "65c238ea3713e39372b580c0"
        }
      ],
      "isDeleted": false,
      "createdAt": "2024-02-06T13:49:30.305Z",
      "updatedAt": "2024-02-06T13:49:30.305Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ReviceQuestionsmodelData?>? data;

  ReviceQuestionsmodel({
    this.status,
    this.result,
    this.data,
  });
  ReviceQuestionsmodel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ReviceQuestionsmodelData>[];
  v.forEach((v) {
  arr0.add(ReviceQuestionsmodelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
