///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentModelDataClassNameTimeTable {
/*
{
  "time": "10am-11am",
  "day": "monday",
  "subject": "657025d48c2337e8d3e2e30d",
  "subjectTeacher": "657021118c2337e8d3e2e307",
  "_id": "65d1b46061241ee42bf91b74"
} 
*/

  String? time;
  String? day;
  String? subject;
  String? subjectTeacher;
  String? Id;

  StudentModelDataClassNameTimeTable({
    this.time,
    this.day,
    this.subject,
    this.subjectTeacher,
    this.Id,
  });
  StudentModelDataClassNameTimeTable.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    day = json['day']?.toString();
    subject = json['subject']?.toString();
    subjectTeacher = json['subjectTeacher']?.toString();
    Id = json['_id']?.toString();
  }
}

class StudentModelDataClassNameClassFaculity {
/*
{
  "subjectTeacher": "657021118c2337e8d3e2e307",
  "subject": "6570261b8c2337e8d3e2e313",
  "_id": "65d1b46061241ee42bf91b72"
} 
*/

  String? subjectTeacher;
  String? subject;
  String? Id;

  StudentModelDataClassNameClassFaculity({
    this.subjectTeacher,
    this.subject,
    this.Id,
  });
  StudentModelDataClassNameClassFaculity.fromJson(Map<String, dynamic> json) {
    subjectTeacher = json['subjectTeacher']?.toString();
    subject = json['subject']?.toString();
    Id = json['_id']?.toString();
  }
}

class StudentModelDataClassName {
/*
{
  "_id": "65d1b46061241ee42bf91b71",
  "school": "65a52f67e6b1f330a3d7673d",
  "classTeacher": "657021118c2337e8d3e2e307",
  "className": "8th",
  "section": "A",
  "subject": "6570261b8c2337e8d3e2e313",
  "classCapcity": 30,
  "classFaculity": [
    {
      "subjectTeacher": "657021118c2337e8d3e2e307",
      "subject": "6570261b8c2337e8d3e2e313",
      "_id": "65d1b46061241ee42bf91b72"
    }
  ],
  "timeTable": [
    {
      "time": "10am-11am",
      "day": "monday",
      "subject": "657025d48c2337e8d3e2e30d",
      "subjectTeacher": "657021118c2337e8d3e2e307",
      "_id": "65d1b46061241ee42bf91b74"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-02-18T07:40:16.767Z",
  "updatedAt": "2024-02-18T07:40:16.767Z",
  "__v": 0
} 
*/

  String? Id;
  String? school;
  String? classTeacher;
  String? className;
  String? section;
  String? subject;
  int? classCapcity;
  List<StudentModelDataClassNameClassFaculity?>? classFaculity;
  List<StudentModelDataClassNameTimeTable?>? timeTable;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  StudentModelDataClassName({
    this.Id,
    this.school,
    this.classTeacher,
    this.className,
    this.section,
    this.subject,
    this.classCapcity,
    this.classFaculity,
    this.timeTable,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  StudentModelDataClassName.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    school = json['school']?.toString();
    classTeacher = json['classTeacher']?.toString();
    className = json['className']?.toString();
    section = json['section']?.toString();
    subject = json['subject']?.toString();
    classCapcity = json['classCapcity']?.toInt();
  if (json['classFaculity'] != null) {
  final v = json['classFaculity'];
  final arr0 = <StudentModelDataClassNameClassFaculity>[];
  v.forEach((v) {
  arr0.add(StudentModelDataClassNameClassFaculity.fromJson(v));
  });
    classFaculity = arr0;
    }
  if (json['timeTable'] != null) {
  final v = json['timeTable'];
  final arr0 = <StudentModelDataClassNameTimeTable>[];
  v.forEach((v) {
  arr0.add(StudentModelDataClassNameTimeTable.fromJson(v));
  });
    timeTable = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class StudentModelData {
/*
{
  "contactNumber": "9100000000",
  "_id": "65701e37b9cdbf994405ddae",
  "rollNumber": 15,
  "school": "65a52f67e6b1f330a3d7673d",
  "admissionId": "",
  "admissionDate": "2023-12-06T07:09:23.902Z",
  "district": "Sample District",
  "districtStudentID": "123456",
  "stateStudentID": "7890",
  "name": "suraj singh",
  "email": "student321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-teacherimg.png",
  "gender": "Male",
  "dob": "24-10-1998",
  "firebaseUid": "tRs34G9tTTbDXnm34i2oCdSNgj03",
  "firebaseSignInProvider": "custom",
  "active": true,
  "isDeleted": false,
  "__t": "Student",
  "createdAt": "2023-12-06T07:09:43.682Z",
  "updatedAt": "2024-01-12T09:53:41.225Z",
  "__v": 0,
  "className": {
    "_id": "65d1b46061241ee42bf91b71",
    "school": "65a52f67e6b1f330a3d7673d",
    "classTeacher": "657021118c2337e8d3e2e307",
    "className": "8th",
    "section": "A",
    "subject": "6570261b8c2337e8d3e2e313",
    "classCapcity": 30,
    "classFaculity": [
      {
        "subjectTeacher": "657021118c2337e8d3e2e307",
        "subject": "6570261b8c2337e8d3e2e313",
        "_id": "65d1b46061241ee42bf91b72"
      }
    ],
    "timeTable": [
      {
        "time": "10am-11am",
        "day": "monday",
        "subject": "657025d48c2337e8d3e2e30d",
        "subjectTeacher": "657021118c2337e8d3e2e307",
        "_id": "65d1b46061241ee42bf91b74"
      }
    ],
    "isDeleted": false,
    "createdAt": "2024-02-18T07:40:16.767Z",
    "updatedAt": "2024-02-18T07:40:16.767Z",
    "__v": 0
  }
} 
*/

  String? contactNumber;
  String? Id;
  int? rollNumber;
  String? school;
  String? admissionId;
  String? admissionDate;
  String? district;
  String? districtStudentID;
  String? stateStudentID;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? T;
  String? createdAt;
  String? updatedAt;
  int? V;
  StudentModelDataClassName? className;

  StudentModelData({
    this.contactNumber,
    this.Id,
    this.rollNumber,
    this.school,
    this.admissionId,
    this.admissionDate,
    this.district,
    this.districtStudentID,
    this.stateStudentID,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.T,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.className,
  });
  StudentModelData.fromJson(Map<String, dynamic> json) {
    contactNumber = json['contactNumber']?.toString();
    Id = json['_id']?.toString();
    rollNumber = json['rollNumber']?.toInt();
    school = json['school']?.toString();
    admissionId = json['admissionId']?.toString();
    admissionDate = json['admissionDate']?.toString();
    district = json['district']?.toString();
    districtStudentID = json['districtStudentID']?.toString();
    stateStudentID = json['stateStudentID']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    T = json['__t']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    className = (json['className'] != null) ? StudentModelDataClassName.fromJson(json['className']) : null;
  }
}

class StudentModel {
/*
{
  "status": true,
  "data": [
    {
      "contactNumber": "9100000000",
      "_id": "65701e37b9cdbf994405ddae",
      "rollNumber": 15,
      "school": "65a52f67e6b1f330a3d7673d",
      "admissionId": "",
      "admissionDate": "2023-12-06T07:09:23.902Z",
      "district": "Sample District",
      "districtStudentID": "123456",
      "stateStudentID": "7890",
      "name": "suraj singh",
      "email": "student321@gmail.com",
      "image": "https://angolazone.s3.amazonaws.com/angolazone-teacherimg.png",
      "gender": "Male",
      "dob": "24-10-1998",
      "firebaseUid": "tRs34G9tTTbDXnm34i2oCdSNgj03",
      "firebaseSignInProvider": "custom",
      "active": true,
      "isDeleted": false,
      "__t": "Student",
      "createdAt": "2023-12-06T07:09:43.682Z",
      "updatedAt": "2024-01-12T09:53:41.225Z",
      "__v": 0,
      "className": {
        "_id": "65d1b46061241ee42bf91b71",
        "school": "65a52f67e6b1f330a3d7673d",
        "classTeacher": "657021118c2337e8d3e2e307",
        "className": "8th",
        "section": "A",
        "subject": "6570261b8c2337e8d3e2e313",
        "classCapcity": 30,
        "classFaculity": [
          {
            "subjectTeacher": "657021118c2337e8d3e2e307",
            "subject": "6570261b8c2337e8d3e2e313",
            "_id": "65d1b46061241ee42bf91b72"
          }
        ],
        "timeTable": [
          {
            "time": "10am-11am",
            "day": "monday",
            "subject": "657025d48c2337e8d3e2e30d",
            "subjectTeacher": "657021118c2337e8d3e2e307",
            "_id": "65d1b46061241ee42bf91b74"
          }
        ],
        "isDeleted": false,
        "createdAt": "2024-02-18T07:40:16.767Z",
        "updatedAt": "2024-02-18T07:40:16.767Z",
        "__v": 0
      }
    }
  ]
} 
*/

  bool? status;
  List<StudentModelData?>? data;

  StudentModel({
    this.status,
    this.data,
  });
  StudentModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <StudentModelData>[];
  v.forEach((v) {
  arr0.add(StudentModelData.fromJson(v));
  });
    data = arr0;
    }
  }
}




